package ifneeded vmdToolBar                                     1.0 [list source [file join $dir/vmdToolBar.tcl]]
package ifneeded vmdRender        	                            1.0 [list source [file join $dir/packages/vmdRender.tcl]]
package ifneeded toolBar                                        1.0 [list source [file join $dir/packages/vmdToolBar.tcl]]
package ifneeded balloon                                        1.0 [list source [file join $dir/packages/balloon.tcl]]
package ifneeded vmdPresets                                     1.0 [list source [file join $dir/packages/vmdPresets.tcl]]
package ifneeded selectionManager                               1.0 [list source [file join $dir/packages/selectionManager.tcl]]
package ifneeded selectionManager                               2.0 [list source [file join $dir/packages/newSelectionManager.tcl]]